### ISSUE TITLE
Gem::use_gemdeps

### ISSUE THREAD

**Issue by michaelrkn** [rvm/rubygems-bundler#60]
I was really excited to see `Gem::use_gemdeps` when I updated to Rubygems 2.2.1 today! If I understand correctly (and my informal testing bears this out), this means that rubygems-bundler is not necessary Rubygems >= 2.2.0 - users can simply set `RUBYGEMS_GEMDEPS=-`. Perhaps the README on rubygems-bundler should note this prominently? If you agree, I'm happy to open a pull request.

**Comment by mpapis** [comment]
hi, I'm so sorry I did not answer earlier, I only now understand that you asked for my approval in my message, please go ahead if you are still interested and have some time for it
